/**
 * Edge Case Tests for table_name
 * AUTO-GENERATED by cohere
 */

describe('table_name Edge Cases', () => {
  const orgId = 'test-org-id';

  describe('Empty Result Sets', () => {
    test('SELECT returns empty array when no rows match', async () => {
      const result = await query(
        'SELECT * FROM table_name WHERE id = $1 AND organization_id = $2',
        ['nonexistent-id', orgId]
      );
      expect(result.rows).toEqual([]);
    });
  });

  describe('Primary Key Edge Cases', () => {
    test('INSERT fails on duplicate primary key', async () => {
      await expect(query(
        'INSERT INTO table_name (id) VALUES ($1)',
        ['existing-id']
      )).rejects.toThrow('duplicate_key');
    });

    test('UPDATE modifies correct row', async () => {
      const result = await query(
        'UPDATE table_name SET updated_at = NOW() WHERE id = $1 AND organization_id = $2 RETURNING id',
        ['target-id', orgId]
      );
      expect(result.rowCount).toBe(1);
    });
  });

  describe('Soft Delete Edge Cases', () => {
    test('SELECT excludes soft-deleted records by default', async () => {
      const result = await query(
        'SELECT * FROM table_name WHERE organization_id = $1',
        [orgId]
      );
      expect(result.rows.every(r => r.deleted_at === null)).toBe(true);
    });
  });
});
